### ISSUE TITLE
Epic Roadmap To Beta Version Of Chatbot

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/chatbot#40]
We've decided to release a beta version of the AsyncAPI Chatbot with the ability to enable chatbot support for Studio and Website and CLI and others.

The following is a list of proposed features for the beta release:
**Target release date: March 2022**

The following list is categorized into 3 sections and is arranged in the level of importance.

**AI**

- [ ] Data migration from WIT.AI to Rasa AI
- [ ] What it will cost to fully migrate to Rasa AI
- [ ] Train Chatbot

**SERVER**

- [ ] Write AsyncAPI file for the chatbot WebSocket API server
- [ ]  Bootstrap glee project using the chatbot AsyncAPI file
- [ ] Migration of the business logic from the old server to the new server
- [ ]  Docker support
- [ ] Deployment to Digitalocean
- [ ] Add support for JSON Schema model
- [ ]  Chatbot capacity to help lift question burden off Lukasz

**CLIENT**

- [ ] Remove custom CLI from chatbot repo
- [ ] Add new command to AsyncAPI CLI (“start chatbot”)
- [ ] Enhance Chatbot User Interface
- [ ] #60
